#
#  -- LAPACK95 EXAMPLE1 makefile (version 1.0) --
#     UNI-C, Denmark; Univ. of Tennessee, USA; NAG Ltd., UK
#     August, 2000
#
include ../make.inc

la_lamch_example: 
	$(YY)

la_gels_example: 
	$(YY)

la_gelss_example: 
	$(YY)

la_gglse_example: 
	$(YY)

la_ggglm_example: 
	$(YY)

la_syev_example: 
	$(YY)

la_hpev_example:
	$(YY)

la_sbev_example: 
	$(YY)

la_stev_example: 
	$(YY)

la_gees_example:
	$(YY)

la_geev_example:
	$(YY)

la_sygv_example: 
	$(YY)

la_sbgv_example:
	$(YY)

la_gesvd_example:
	$(YY)

la_ggsvd_example: 
	$(YY)

la_gesv_example:	
	$(YY)

la_gesvx_example: 
	$(YY)

la_gbsv_example: 
	$(YY)

la_gbsvx_example:
	$(YY)

la_syevx_example: 
	$(YY)

la_sbevx_example: 
	$(YY)

la_stevx_example:
	$(YY)

la_gtsv_example:
	$(YY)

la_gtsvx_example:
	$(YY)

la_hpevx_example:
	$(YY)

la_posv_example:
	$(YY)

la_posvx_example:
	$(YY)

la_ppsv_example:
	$(YY)

la_ppsvx_example: 
	$(YY)

la_geesx_example:
	$(YY)

la_geevx_example: 
	$(YY)

la_sygvx_example:
	$(YY)

la_sbgvx_example:
	$(YY)

la_pbsv_example: 
	$(YY)

la_pbsvx_example: 
	$(YY)

la_ptsv_example: 
	$(YY)

la_ptsvx_example: 
	$(YY)

la_sysv_example: 
	$(YY)

la_hesv_example: 
	$(YY)

la_sysvx_example: 
	$(YY)

la_spsv_example: 
	$(YY)

la_spsvx_example: 
	$(YY)

la_gelsy_example: 
	$(YY)

la_syevr_example:
	$(YY)

la_stevr_example: 
	$(YY)

la_gges_example:
	$(YY)

la_ggesx_example: 
	$(YY)

la_ggev_example:
	$(YY)

la_ggevx_example:
	$(YY)

la_hpgv_example:
	$(YY)

la_hpgvx_example:
	$(YY)

clean:
	'rm' -f *.o *.mod *.a core la_*example
