#
#  -- LAPACK90 interface driver routine (version 0.0) --
#     UNI-C, Denmark; Univ. of Tennessee, USA; NAG Ltd., UK
#     May 31, 1996
#
include ../make.inc
#
# LAPACK_PATH = $(HOME)/LAPACK3
# 
# #ARCH    = rs6000
# ARCH    = LINUXi386
# 
# LAPACK77 = $(LAPACK_PATH)/lapack_$(ARCH).a
# TMG77    = $(LAPACK_PATH)/tmglib_$(ARCH).a
# BLAS     = $(LAPACK_PATH)/blas_$(ARCH).a
# TESTLIB  = LIB/testlib_$(ARCH).a
# 
# FFLAGS = -g $(FFLAGS)
# 
# XX1 = 'rm' -f $@; \
# 	'rm' -f $@.res; \
# 	$(FC) $(OPTL) $@ $(OPTS2) $@.$(SUF) $(OPTLIB) la_sstevr.o $(LIBS); \
# 	$@ < $@.dat > $@.res
# #	'rm' -f $@; 

########### ge, General Linear Systems #############
ssbgvxet:
	$(XX)
	
dsbgvxet:
	$(XX)
	
chbgvxet:
	$(XX)
	
zhbgvxet:
	$(XX)	

ssyevret:
	$(XX)
	
dsyevret:
	$(XX)

cheevret:
	$(XX)
	
zheevret:
	$(XX)

sspgvxet:
	$(XX)

dspgvxet:
	$(XX)

chpgvxet:
	$(XX)
	
zhpgvxet:
	$(XX)
	
ssygvxet:
	$(XX)
	
dsygvxet:
	$(XX)
	
chegvxet:
	$(XX)
	
zhegvxet:
	$(XX)	

sstevret:
	$(XX)

dstevret:
	$(XX)
	
sggesxet:
	$(XX)
	
dggesxet:
	$(XX)
	
cggesxet:
	$(XX)
	
zggesxet:
	$(XX)	
	
sggevxet:
	$(XX)
	
dggevxet:
	$(XX)
	
cggevxet:
	$(XX)
	
zggevxet:
	$(XX)	

sggevet:
	$(XX)
	
dggevet:
	$(XX)
	
cggevet:
	$(XX)
	
zggevet:
	$(XX)	

sggeset:
	$(XX)
	
dggeset:
	$(XX)
	
cggeset:
	$(XX)
	
zggeset:
	$(XX)

ssbgvdet:
	$(XX)

dsbgvdet:
	$(XX)

chbgvdet:
	$(XX)

zhbgvdet:
	$(XX)

sspgvdet: 
	$(XX)

dspgvdet:
	$(XX)

chpgvdet:
	$(XX)

zhpgvdet:
	$(XX)

ssygvdet:
	$(XX)
	
dsygvdet:
	$(XX)	

chegvdet:
	$(XX)
	
zhegvdet:
	$(XX)	

sgesddet:
	$(XX)

dgesddet:
	$(XX)
	
cgesddet:
	$(XX)
	
zgesddet:
	$(XX)	

sgelsdet:
	$(XX)

dgelsdet:
	$(XX)
	
cgelsdet:
	$(XX)
	
zgelsdet:
	$(XX)	

sgelsyet:
	$(XX)
	
dgelsyet:
	$(XX)
	
cgelsyet:
	$(XX)
	
zgelsyet:
	$(XX)	

sgeevxst:
	$(XX)

sgesvst:
	$(XX)

zgesvmg:
	$(XX)

cgesvmg:
	$(XX)

dgesvmg:
	$(XX)

sgesvmg:
	$(XX)

sggsvdet:
	$(XX)

dggsvdet:
	$(XX)

cggsvdet:
	$(XX)

zggsvdet:
	$(XX)

sgegvet:
	$(XX)

dgegvet:
	$(XX)

cgegvet:
	$(XX)

zgegvet:
	$(XX)

sgegset:
	$(XX)

dgegset:
	$(XX)

cgegset:
	$(XX)

zgegset:
	$(XX)

ssbgvet:
	$(XX)

dsbgvet:
	$(XX)

chbgvet:
	$(XX)

zhbgvet:
	$(XX)

sspgvet:
	$(XX)

dspgvet:
	$(XX)

chpgvet:
	$(XX)

zhpgvet:
	$(XX)

sgesvdet:
	$(XX)

dgesvdet:
	$(XX)

cgesvdet:
	$(XX)

zgesvdet:
	$(XX)

sgeevxet:
	$(XX)

dgeevxet:
	$(XX)

cgeevxet:
	$(XX)

zgeevxet:
	$(XX)

sgeevet:
	$(XX)

dgeevet:
	$(XX)

cgeevet:
	$(XX)

zgeevet:
	$(XX)

sgeesxet:
	$(XX)

dgeesxet:
	$(XX)

cgeesxet:
	$(XX)

zgeesxet:
	$(XX)

sgeeset:
	$(XX)

dgeeset:
	$(XX)

cgeeset:
	$(XX)

zgeeset:
	$(XX)

sstevxet:
	$(XX)

dstevxet:
	$(XX)

sstevdet:
	$(XX)

dstevdet:
	$(XX)

sstevet:
	$(XX)

dstevet:
	$(XX)

ssbevxet:
	$(XX)

dsbevxet:
	$(XX)

chbevxet:
	$(XX)

zhbevxet:
	$(XX)

ssbevdet:
	$(XX)

dsbevdet:
	$(XX)

chbevdet:
	$(XX)

zhbevdet:
	$(XX)

ssbevet:
	$(XX)

dsbevet:
	$(XX)

chbevet:
	$(XX)

zhbevet:
	$(XX)

sspevxet:
	$(XX)

dspevxet:
	$(XX)

chpevxet:
	$(XX)

zhpevxet:
	$(XX)

sspevdet:
	$(XX)

dspevdet:
	$(XX)

chpevdet:
	$(XX)

zhpevdet:
	$(XX)

sspevet:
	$(XX)

dspevet:
	$(XX)

chpevet:
	$(XX)

zhpevet:
	$(XX)

sggglmet:
	$(XX)

dggglmet:
	$(XX)

cggglmet:
	$(XX)

zggglmet:
	$(XX)

sgglseet:
	$(XX)

dgglseet:
	$(XX)

cgglseet:
	$(XX)

zgglseet:
	$(XX)

sgelsxet:
	$(XX)

dgelsxet:
	$(XX)

cgelsxet:
	$(XX)

zgelsxet:
	$(XX)

sgelsset:
	$(XX)

dgelsset:
	$(XX)

cgelsset:
	$(XX)

zgelsset:
	$(XX)

sgelset:
	$(XX)

dgelset:
	$(XX)

cgelset:
	$(XX)

zgelset:
	$(XX)

sspsvxet:
	$(XX)

dspsvxet:
	$(XX)

cspsvxet:
	$(XX)

zspsvxet:
	$(XX)

chpsvxet:
	$(XX)

zhpsvxet:
	$(XX)

ssysvxet:
	$(XX)

dsysvxet:
	$(XX)

csysvxet:
	$(XX)

zsysvxet:
	$(XX)

chesvxet:
	$(XX)

zhesvxet:
	$(XX)

sptsvxet:
	$(XX)

dptsvxet:
	$(XX)

cptsvxet:
	$(XX)

zptsvxet:
	$(XX)

spbsvxet:
	$(XX)

dpbsvxet:
	$(XX)

cpbsvxet:
	$(XX)

zpbsvxet:
	$(XX)

sppsvxet:
	$(XX)

dppsvxet:
	$(XX)

cppsvxet:
	$(XX)

zppsvxet:
	$(XX)

sposvxet:
	$(XX)

dposvxet:
	$(XX)

cposvxet:
	$(XX)

zposvxet:
	$(XX)

sgtsvxet:
	$(XX)

dgtsvxet:
	$(XX)

cgtsvxet:
	$(XX)

zgtsvxet:
	$(XX)

sgbsvxet:
	$(XX)

dgbsvxet:
	$(XX)

cgbsvxet:
	$(XX)

zgbsvxet:
	$(XX)

sspsvet:
	$(XX)

dspsvet:
	$(XX)

cspsvet:
	$(XX)

zspsvet:
	$(XX)

chpsvet:
	$(XX)

zhpsvet:
	$(XX)

ssysvet:
	$(XX)

dsysvet:
	$(XX)

csysvet:
	$(XX)

zsysvet:
	$(XX)

chesvet:
	$(XX)

zhesvet:
	$(XX)

sptsvet:
	$(XX)

dptsvet:
	$(XX)

cptsvet:
	$(XX)

zptsvet:
	$(XX)

spbsvet:
	$(XX)

dpbsvet:
	$(XX)

cpbsvet:
	$(XX)

zpbsvet:
	$(XX)

sppsvet:
	$(XX)

dppsvet:
	$(XX)

cppsvet:
	$(XX)

zppsvet:
	$(XX)

sposvet:
	$(XX)

dposvet:
	$(XX)

cposvet:
	$(XX)

zposvet:
	$(XX)

sgtsvet:
	$(XX)

dgtsvet:
	$(XX)

cgtsvet:
	$(XX)

zgtsvet:
	$(XX)

zgbsvet:
	$(XX)

cgbsvet:
	$(XX)

dgbsvet:
	$(XX)

sgbsvet:
	$(XX)

sgesvxet:
	$(XX)

cgesvxet:
	$(XX)

dgesvxet:
	$(XX)

zgesvxet:
	$(XX)

sgerfset:
	$(XX)

cgerfset:
	$(XX)

dgerfset:
	$(XX)

zgerfset:
	$(XX)

sgetriet:
	$(XX)

dgetriet:
	$(XX)

cgetriet:
	$(XX)

zgetriet:
	$(XX)

sgeequet:
	$(XX)

cgeequet:
	$(XX)

dgeequet:
	$(XX)

zgeequet:
	$(XX)

sgesvet:
	 $(XX)

cgesvet:
	 $(XX)

dgesvet:
	 $(XX)

zgesvet:
	 $(XX)

sgetrfet:
	$(XX)

cgetrfet:
	$(XX)

dgetrfet:
	$(XX)

zgetrfet:
	$(XX)

sgetrset:
	$(XX)

cgetrset:
	$(XX)

dgetrset:
	$(XX)

zgetrset:
	$(XX)

########### sy/he, Symetric and Hermitian Eigenproblem #####

ssyevet:
	$(XX)

cheevet:
	$(XX)

dsyevet:
	$(XX)

zheevet:
	$(XX)

ssyevdet:
	$(XX)

cheevdet:
	$(XX)

dsyevdet:
	$(XX)

zheevdet:
	$(XX)

ssyevxet:
	$(XX)

cheevxet:
	$(XX)

dsyevxet:
	$(XX)

zheevxet:
	$(XX)

ssygstet:
	$(XX)

chegstet:
	$(XX)

dsygstet:
	$(XX)

zhegstet:
	$(XX)

ssygvet:
	$(XX)

chegvet:
	$(XX)

dsygvet:
	$(XX)

zhegvet:
	$(XX)

ssytrdet:
	$(XX)

chetrdet:
	$(XX)

dsytrdet:
	$(XX)

zhetrdet:
	$(XX)

sorgtret:
	$(XX)

cungtret:
	$(XX)

dorgtret:
	$(XX)

zungtret:
	$(XX)

########### potrf needed for the sy/he group ###############

spotrfet:
	$(XX)

cpotrfet:
	$(XX)

dpotrfet:
	$(XX)

zpotrfet:
	$(XX)

clean: 
	'rm' -f *.o *.l *.mod *.res *et *mg core
