name: ci_linux

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_linux.yml"


jobs:

  cmake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: prereqs
      run: |
        sudo apt update -yq
        sudo apt install gfortran liblapack-dev

    - run: cmake -B build --install-prefix=${{ runner.temp }}
    - run: cmake --build build
    - run: ctest --test-dir build --preset default

    - run: cmake --install build
